# -*- coding: utf-8 -*-
"""Proccessing Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eq6xwRN1vWfUCpESQzcdooTtES4caLq0
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Numpy merupakan library python yang digunakan dalam matriks. Matplotlib merupakan library python yang digunakan untuk presentasi atau grafik"""

dataset = pd.read_csv('Data Badan.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(X)

print(y)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

print(X)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 2, random_state = 1)

print(x_train)